--上一月开始日期
SELECT TRUNC(TRUNC(SYSDATE,'MONTH') - 1,'MONTH') FROM DUAL;

--上一月结束日期
SELECT TRUNC(SYSDATE,'MONTH')-1 FROM DUAL;

--OR
SELECT TRUNC(SYSDATE,'MON') FROM DUAL;
--OR
SELECT TRUNC(SYSDATE,'MONTH') FROM DUAL;

--上一月开始日期和结束日期
SELECT TRUNC(ADD_MONTHS(SYSDATE, -1), 'MM') AS FIRST_DAY_LAST_MONTH,TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -1))) AS LAST_DAY_LAST_MONTH FROM DUAL;

--当前月开始日期和结束日期
SELECT TRUNC(SYSDATE, 'MM'),TRUNC(ADD_MONTHS (SYSDATE, 1), 'MM')-1 FROM DUAL;

--当前年开始日期和结束日期
SELECT TRUNC(SYSDATE,'YEAR'),ADD_MONTHS(TRUNC(SYSDATE,'YEAR'),'12')-1 FROM DUAL;
--OR
SELECT TRUNC(SYSDATE,'YYYY'),ADD_MONTHS(TRUNC(SYSDATE,'YYYY'),'12')-1 FROM DUAL;
--OR
SELECT TRUNC(SYSDATE,'YYY'),ADD_MONTHS(TRUNC(SYSDATE,'YYY'),'12')-1 FROM DUAL;
--OR
SELECT TRUNC(SYSDATE,'YY'),ADD_MONTHS(TRUNC(SYSDATE,'YY'),'12')-1 FROM DUAL;
--OR
SELECT TRUNC(SYSDATE,'Y'),ADD_MONTHS(TRUNC(SYSDATE,'Y'),'12')-1 FROM DUAL;


--当前日期
SELECT TRUNC(SYSDATE,'DDD') FROM DUAL;
--OR
SELECT TRUNC(SYSDATE,'DD') FROM DUAL;
--OR
SELECT TRUNC(SYSDATE,'J') FROM DUAL;


SELECT TRUNC(SYSDATE,'HH') FROM DUAL;

SELECT TRUNC(SYSDATE,'HH12') FROM DUAL;

SELECT TRUNC(SYSDATE,'HH24') FROM DUAL;

SELECT TRUNC(SYSDATE,'MI') FROM DUAL;

